services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports: 
      - 1433:1433
    environment: 
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=User123!

  app:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:5001"
      - "5000:5000"
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - database
    command: bash -c "
      dotnet dev-certs https &&
      dotnet run --project ./NewsAggregator.WebUI/NewsAggregator.WebAPI.csproj --launch-profile 'Docker'
      "

